version: '3'
services:

  db:
    build: .
    image: postgres
    ports:
      - "5435:5432"
    environment:

      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbpostgrest

    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"