version: '3'
services:

  ### DB START
  db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtodos

    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"