version: '3'
services:

  ### DB START
  # This is the database to which the all the other components in the stack will connect and interact with
  # (but mostly it's PostgREST that is going to be responsible for the bulk of the db traffic)
  # Having the database in a container is very convenient in development but in production you will
  # use a separate database instance, like Amazon RDS, i.e. in production this section will be
  # commented and in the .env file you will specify the ip of your separate database instance
  db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtodos

    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"